spring.application.name=segment-metric-service

# ==============================================================
# 1. Master DataSource (Write - Insert/Update/Delete)
# Prefix: spring.datasource.master
# ==============================================================
spring.datasource.master.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.master.jdbc-url=jdbc:mysql://localhost:3306/replication_test?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
spring.datasource.master.username=admin
spring.datasource.master.password=admin_password

# [HikariCP - Master]
spring.datasource.master.hikari.maximum-pool-size=20
spring.datasource.master.hikari.minimum-idle=10
spring.datasource.master.hikari.connection-timeout=30000
spring.datasource.master.hikari.pool-name=Master-HikariCP

# ==============================================================
# 2. Slave DataSource (Read Only - Batch Select)
# Prefix: spring.datasource.slave
# ==============================================================
spring.datasource.slave.driver-class-name=com.mysql.cj.jdbc.Driver

# Slave? ?? DB? (?? ????)
spring.datasource.slave.jdbc-url=jdbc:mysql://localhost:3306/replication_test?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
spring.datasource.slave.username=admin
spring.datasource.slave.password=admin_password

# [HikariCP - Slave]
# spring.datasource.slave.hikari.maximum-pool-size=100
spring.datasource.slave.hikari.minimum-idle=20
spring.datasource.slave.hikari.connection-timeout=60000
spring.datasource.slave.hikari.read-only=true
spring.datasource.slave.hikari.pool-name=Slave-HikariCP

# ==============================================================
# 3. JPA & Common Settings
# ==============================================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false

# ?? ?? ??? ???
batch.chunk-size=1000

# Actuator - Prometheus ????? ??
management.endpoints.web.exposure.include=prometheus,health,metrics
management.endpoint.prometheus.enabled=true
management.metrics.tags.application=segment-metric-service